import styles from "./barang/barang.module.css"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className={styles.header}>
          <Image src={"/images/SANGJUARA.png"} alt="Logo UTI" width={320} height={60} priority />
        </header>

        <main>{children}</main>
        {/* tambhakan tag toaster untuk sonner */}
        <Toaster position="bottom-center" style={{backgroundColor: "#33333333", color:"#fff"}} />

        <footer className={styles.footer}>
          &copy; 2025 - IF 23 FX
        </footer>
      </body>
    </html>
  );
}
